# Generated by Django 5.0.3 on 2024-04-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_password_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='password',
        ),
    ]
