# Generated by Django 5.0.3 on 2024-04-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField()),
                ('tdate', models.DateField()),
            ],
            options={
                'db_table': 'date',
            },
        ),
    ]
