# Generated by Django 5.0.3 on 2024-04-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_date_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
