# Generated by Django 5.0.3 on 2024-04-27 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_delete_date'),
        ('myadmin', '0002_alter_plan_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.plan')),
            ],
        ),
    ]
