# Generated by Django 5.0.3 on 2024-04-27 11:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_initial'),
        ('myadmin', '0005_city_hotels_places_state_travel_area_hotel_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.BigIntegerField()),
                ('message', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'inquiry',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('reg_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_mode', models.CharField(default='online', max_length=40)),
                ('booking_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='completed', max_length=30)),
                ('adult', models.CharField(default='', max_length=30)),
                ('child', models.CharField(default='', max_length=30)),
                ('plan', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.plan')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField()),
                ('tdate', models.DateField()),
                ('plan', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.plan')),
            ],
            options={
                'db_table': 'date',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BigIntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=40)),
                ('amount', models.BigIntegerField()),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.booking')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.login')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
