# Generated by Django 5.0.3 on 2024-04-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
