# Generated by Django 5.0.3 on 2024-04-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_abc_plan_remove_booking_plan_and_more'),
        ('myadmin', '0002_alter_plan_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='area',
        ),
        migrations.RemoveField(
            model_name='place',
            name='area',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='plan_hotel',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
        migrations.RemoveField(
            model_name='place',
            name='state',
        ),
        migrations.RemoveField(
            model_name='plan_place',
            name='place',
        ),
        migrations.DeleteModel(
            name='Places',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='plan_place',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='plan_hotel',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
        migrations.DeleteModel(
            name='Plan_Place',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Plan_Hotel',
        ),
    ]
