# Generated by Django 5.0.3 on 2024-04-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_customer_profile_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(blank=True, default='login.png', null=True, upload_to='media'),
        ),
    ]
