# Generated by Django 5.0.3 on 2024-04-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_alter_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(blank=True, default='media/login.png', null=True, upload_to='media'),
        ),
    ]
