# Generated by Django 5.0.3 on 2024-04-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_alter_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
